- name: set locale
  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}
  sudo: true

- name: set /etc/localtime
  file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link force=yes
  sudo: true

- name: set /etc/timezone
  template: src=etc/timezone dest=/etc/timezone
  notify: update tzdata
  sudo: true
