
  - name: Create java repo list
    shell: echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" | tee /etc/apt/sources.list.d/webupd8team-java.list
    sudo: true

  - name: Add repo key
    command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
    sudo: true

  - name: Accept java license
    shell: echo 'oracle-java7-installer shared/accepted-oracle-license-v1-1 select true' | debconf-set-selections
    sudo: true

  - name: Update
    command: apt-get update -y
    sudo: true

  - name: Install java 7
    command: apt-get install oracle-java7-set-default -y
    sudo: true
