openhab_install_dir: "{{ ansible_env.HOME }}/opt/openhab"
openhab_version: 1.6.1
habmin_version: 0.1.3-snapshot
habmin_openhab_version: 1.5.0-SNAPSHOT
#openhab_designer_platform: linux64bit # win|linux|macosx64|linux64bit

rfxcom_tty: ttyRFXCOM
zwave_tty: ttyZWAVE
